behaviors:
  UnitAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 124
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    max_steps: 5.0e7
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 5000
    max_steps: 250000